#!/bin/bash
# RClone Config file
RCLONE_CONFIG=/root/.config/rclone/rclone.conf
export RCLONE_CONFIG

#exit if running
if [[ "`pidof -x $(basename $0) -o %PPID`" ]]; then exit; fi

# Move older local files to the cloud
/usr/bin/rclone move /mnt/storage/local/TV\ Shows/ gcrypt:TV\ Shows/ --log-file /root/rclone/logs/upload.log -v --exclude-from /root/rclone/excludes  --user-agent animosityapp --fast-list --max-transfer 31G--transfers 1